name: CommandFramework
version: '${project.version}'
main: me.unleqitq.commandframework.CommandFramework
api-version: 1.15
load: STARTUP
authors: [ UnleqitQ ]
softdepend:
  - SuperVanish
  - PremiumVanish